### ISSUE TITLE
Add Terraform Tags

### ISSUE THREAD

**Issue by pogzie** [alexchrisramos/aws-tf-provision#2]
- Add a name to worker/cp/bastion/registry. https://stackoverflow.com/questions/67276673/how-to-specify-instance-name-as-part-of-aws-instance 
- Use `tags = merge ()` inside the specific sections for worker/cp/bastion/registry. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/resource-tagging   
- Use `key = each.key` then tag it as CP1/WK1 etc. This should list it as CP01, CP02 and so on. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/resource-tagging#managing-individual-resource-tags and also https://groups.google.com/g/terraform-tool/c/5alRWqPiYgA
- Adding the owner to the instance name should also be considered. Again `tags = merge()` can be utilized for this purpose.

**Comment by alexchrisramos** [comment]
Fixed on #11
