### ISSUE TITLE
Show Private IP along with Public IP

### ISSUE THREAD

**Issue by pogzie** [alexchrisramos/aws-tf-provision#3]
For the purpose of easily identifying nodes for airgap install we should also output the private IP. 

Also if we have a tf env var for airgap deploy, we can set `associate_public_ip` to `false` via a conditional statement discussed in https://blog.gruntwork.io/terraform-tips-tricks-loops-if-statements-and-gotchas-f739bbae55f9#0223

**Comment by alexchrisramos** [comment]
Completed on PR [#9](https://github.com/alexchrisramos/aws-tf-provision/pull/9)
